GET http://localhost:8080/plant/63c6bc797db8505332e7e106
###

POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
"commonName":"Moringa", 
"localName":"Imoringa",
"family":"Moringaceae", 
"genus":"Moringa", 
"isMedicinal":"True",
"flowerColor":"White",
"isEdible":"True",
"scientificName":"Moringa olifera"
}
###

POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
"commonName":"Amaranth", 
"localName":"Efo green",
"family":"Amaranthaceae", 
"genus":"Amaranthus", 
"isMedicinal":"False",
"flowerColor":"Red",
"isEdible":"True",
"scientificName":"Amarathus tricolor"
}
###

DELETE http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "commonName": "Bitter Leaf",
    }

    GET http://localhost:8080/contacts/