GET http://localhost:8080/plant
###

POST http://localhost:8080/plant HTTP/1.1
content-type: application/json

{
    "commonName":"Moringa", 
    "localName":"Imoringa",
    "family":"Moringaceae", 
    "genus":"Moringa", 
    "isMedicinal":"True",
    "flowerColor":"White",
    "isEdible":"True",
    "scientificName":"Moringa olifera"
}
###

POST http://localhost:8080/plant HTTP/1.1
content-type: application/json

{
"commonName":"Amaranth", 
"localName":"Efo green",
"family":"Amaranthaceae", 
"genus":"Amaranthus", 
"isMedicinal":"False",
"flowerColor":"Red",
"isEdible":"True",
"scientificName":"Amarathus tricolor"
}
###

PUT http://localhost:8080/plant/63caf432e56efb9774886f13 HTTP/1.1
content-type: application/json

{
"commonName":"Amaranth", 
"localName":"Efo green",
"family":"Amaranthaceae", 
"genus":"Amaranthus", 
"isMedicinal":"False",
"flowerColor":"Red",
"isEdible":"True",
"scientificName":"Amaranthus tricolor"
}
###


DELETE http://localhost:8080/plant/63caf525e56efb9774886f1


###
GET https://plant-api.onrender.com/plant/63cac60b1148deb27fc412dc
###